// timestamp events
const TIMESTAMPS = {
   UPDATE: "TIMESTAMPS_UPDATE"
};

// vehicle events
const VEHICLES = {
   UPDATE_ALL: "VEHICLES_UPDATE_ALL",
   ADD_SELECTED: "VEHICLES_ADD_SELECTED",
   REMOVE_SELECTED: "VEHICLES_REMOVE_SELECTED",
   UPDATE_SELECTED: "VEHICLES_UPDATE_SELECTED"
};

// control events
const CONTROLS = {
   UPDATE_SLIDER: "CONTROLS_UPDATE_SLIDER",
   UPDATE_RANGE: "CONTROLS_UPDATE_RANGE",
   UPDATE_INTERVAL: "CONTROLS_UPDATE_INTERVAL"
};

// control types for `lastInteraction` value
const CONTROL_TYPES = {
   SLIDER: "SLIDER",
   RANGE: "RANGE",
   INTERVAL: "INTERVAL"
};

const CONSTRAINTS = {
   // BASIC ACTIONS
   REFRESH_DATA: "CONSTRAINTS/REFRESH_DATA",

   // GEOFENCE CONSTRAINTS
   GEOFENCES: {
      UPDATE_ALL: "CONTRAINTS/GEOFENCES/UPDATE_ALL",
      CLEAR_ALL: "CONTRAINTS/GEOFENCES/CLEAR_ALL",
      INBOUND: {
         CLEAR: "CONTRAINTS/GEOFENCES/INBOUND/CLEAR",
         UPDATE: "CONTRAINTS/GEOFENCES/INBOUND/UPDATE"
      },
      OUTBOUND: {
         CLEAR: "CONTRAINTS/GEOFENCES/OUTBOUND/CLEAR",
         UPDATE: "CONTRAINTS/GEOFENCES/OUTBOUND/UPDATE"
      }
   },

   // DATE RANGE CONSTRAINTS
   DATE_RANGE: {
      CLEAR_ALL: "CONTRAINTS/DATE_RANGE/CLEAR_ALL",
      START: {
         CLEAR: "CONTRAINTS/DATE_RANGE/START/CLEAR",
         UPDATE: "CONTRAINTS/DATE_RANGE/START/UPDATE"
      },
      END: {
         CLEAR: "CONTRAINTS/DATE_RANGE/END/CLEAR",
         UPDATE: "CONTRAINTS/DATE_RANGE/END/UPDATE"
      }
   },

   // DAY OF WEEK CONSTRAINTS
   DAY_OF_WEEK: {
      CLEAR: "CONSTRAINTS/DAY_OF_WEEK/CLEAR",
      UPDATE: "CONSTRAINTS/DAY_OF_WEEK/UPDATE",
      ADD: "CONSTRAINTS/DAY_OF_WEEK/ADD",
      REMOVE: "CONSTRAINTS/DAY_OF_WEEK/REMOVE",
      TOGGLE: "CONSTRAINTS/DAY_OF_WEEK/TOGGLE"
   },

   // TIME OF DAY CONSTRAINTS
   TIME_OF_DAY: {
      ARRIVAL: {
         CLEAR: "CONSTRAINTS/TIME_OF_DAY/ARRIVAL/CLEAR",
         UPDATE: "CONSTRAINTS/TIME_OF_DAY/ARRIVAL/UPDATE"
      },
      DEPARTURE: {
         CLEAR: "CONSTRAINTS/TIME_OF_DAY/DEPARTURE/CLEAR",
         UPDATE: "CONSTRAINTS/TIME_OF_DAY/DEPARTURE/UPDATE"
      }
   },

   // TRIP TIME/DISTANCE CONSTRAINTS
   TRIP_TIME: {
      CLEAR: "CONSTRAINTS/TRIP_TIME/CLEAR",
      UPDATE: "CONSTRAINTS/TRIP_TIME/UPDATE"
   },
   TRIP_DISTANCE: {
      CLEAR: "CONSTRAINTS/TRIP_DISTANCE/CLEAR",
      UPDATE: "CONSTRAINTS/TRIP_DISTANCE/UPDATE"
   },

   // VEHICLE SELECTION CONSTRAINTS
   VEHICLES: {
      UPDATE: "CONSTRAINTS/VEHICLES/UPDATE",
      CLEAR: "CONSTRAINTS/VEHICLES/CLEAR"
   },

   // DATA SET CONSTRAINTS
   DATA_SET: {
      TOGGLE: "CONSTRAINTS/DATA_SET/TOGGLE"
   },

   // SNAPSHOT CONSTRAINTS
   SNAPSHOT: {
      TOGGLE: "CONSTRAINTS/SNAPSHOT/TOGGLE",
      RESOLUTION: {
         UPDATE: "CONSTRAINTS/SNAPSHOT/RESOLUTION/UPDATE"
      },
      SLIDER: {
         UPDATE: "CONSTRAINTS/SNAPSHOT/SLIDER/UPDATE"
      }
   },

   // ADVANCED SETTINGS CONSTRAINTS
   ADVANCED_SETTINGS: {
      SAMPLING_RATE: {
         UPDATE: {
            SOFT: "ADVANCED_SETTINGS/SAMPLING_RATE/UPDATE/SOFT",
            HARD: "ADVANCED_SETTINGS/SAMPLING_RATE/UPDATE/HARD"
         }
      }
   }
};

const DATA_UPLOAD = {
   DATA: {
      UPDATE: "DATA_UPLOAD/DATA/UPDATE",
      CLEAR: "DATA_UPLOAD/DATA/CLEAR"
   },
   IGNORED: {
      REMOVE: "DATA_UPLOAD/IGNORED/REMOVE",
      ADD: "DATA_UPLOAD/IGNORED/ADD",
      UPDATE: "DATA_UPLOAD/IGNORED/UPDATE",
      CLEAR: "DATA_UPLOAD/IGNORED/CLEAR"
   },
   TABLE_CONFIG: {
      UPDATE: "DATA_UPLOAD/TABLE_CONFIG/UPDATE",
      CLEAR: "DATA_UPLOAD/TABLE_CONFIG/CLEAR"
   }
};

const CROSSFILTER_DATA = {
   UPDATE: "CROSSFILTER_DATA/UPDATE"
};

module.exports = {
   TIMESTAMPS,
   VEHICLES,
   CONTROLS,
   CONTROL_TYPES,
   CONSTRAINTS,
   DATA_UPLOAD,
   CROSSFILTER_DATA
};
